#DESENVOLVA UMA LÓGICA QUE LEIA O PESA E A ALTURA DE UMA PESSOA,CALCULE SEU IMC E MOSTRE SEU STATUS,DE ACORDO COM A TABELA ABAIXO:
# ABAIXO DE 18.5: ABAIXO DO PESO.
# ENTRE 18.5 E 25: PESO IDEAL.
# 25 ATÉ 30 : SOBREPESO.
# 30  40  : OBESIDADE.
# ACIMA DE 40: OBESIDADE MORBIDA.