# A COMFEDERAÇAO PRECISA DE UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO DE UM ATLETA E MOSTRE SUA CATEGORIA, DE ACORDO COM SUA IDADE:
# ATÉ 9 ANOS : MIRIM
# ATÉ 14 ANOS : INFANTIL
# ATÉ 19 ANOS : JUNIOR
# ATÉ 20 ANOS : SENIOR
# ACIMA DE 20 ANOS : MASTER